---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway-applications
  namespace: gateway-api-ns
spec:
  gatewayClassName: cloud-provider-kind
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    allowedRoutes:
      namespaces:
        from: All
