---
apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: auth-ns
type: Opaque
stringData:
  DATABASE_URL: postgres://user:password@db-auth-service:5432/auth_db?sslmode=disable
  MASTER_KEY: super-secret-master-key
  PORT: "8001"
  POSTGRES_DB: auth_db
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  DB_HOST: db-auth-service
  DB_PORT: "5432"
