---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: auth-ns
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: "25%"
      maxUnavailable: "25%"
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: auth-service:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            periodSeconds: 10
            initialDelaySeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            periodSeconds: 10
            initialDelaySeconds: 15
          ports:
            - containerPort: 8001
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: DATABASE_URL
            - name: MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: MASTER_KEY
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: PORT
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 70m
              memory: 50Mi
