---
apiVersion: v1
kind: Secret
metadata:
  name: evaluation-db-secret
  namespace: evaluation-ns
type: Opaque
stringData:
  MASTER_KEY: super-secret-master-key
  REDIS_URL: redis://redis-service:6379
  AUTH_SERVICE_URL: http://auth-service.auth-ns:80/auth-service
  FLAG_SERVICE_URL: http://flag-service.flag-ns:80/flag-service
  TARGETING_SERVICE_URL: http://targeting-service.targeting-ns:80/targeting-service
  # SERVICE_API_KEY: XX
  AWS_SQS_URL: XXX
  AWS_REGION: XXX
  PORT: "8004"
  AWS_ACCESS_KEY_ID: XXX
  AWS_SECRET_ACCESS_KEY: XXX
  AWS_SESSION_TOKEN: XXX
