---
apiVersion: v1
kind: Secret
metadata:
  name: flag-secrets
  namespace: flag-ns
type: Opaque
stringData:
  PORT: "8002"
  AUTH_SERVICE_URL: http://auth-service.auth-ns:80/auth-service
  POSTGRES_USER: devops
  POSTGRES_DB: flag_db
  DB_HOST: "127.0.0.1"
  DB_PORT: "5432"
  CLOUDSQL_CONNECTION_NAME: ces-igniteprogram:southamerica-east1:sql-rhuan-flag
  PROJECT_ID: ces-igniteprogram
  NAME_SECRET_MANAGER: sm-flag-db
