apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flag-ns

# 1. Correção do Ciclo: Liste os arquivos explicitamente
resources:
- flag-service-deployment.yaml
- flag-health-check.yaml
- flag-netpol.yaml
- flag-service-configmap.yaml
- flag-service-pdb.yaml
- flag-service-secret.yaml
- flag-service-serviceaccount.yaml
- flag-service-svc.yaml
- flag-service-hpa.yaml
- flag-db-migration-job.yaml

# 2. Correção do Warning: Usando a nova sintaxe de labels
labels:
- includeSelectors: true
  pairs:
    app: flag-service

# (O bloco patchesStrategicMerge foi removido, pois o deployment já está em resources)

images:
- name: flag-service
  newName: southamerica-east1-docker.pkg.dev/ces-igniteprogram/artreg-flag/flag-service
  newTag: cade864676df07941b62cceb7038d5b354be73d6
