events { worker_connections 1024; }

http {
    # Melhora a performance
    sendfile on;

    server {
        listen 8080;

        # 1. Auth Service
        # Sem barra no final para garantir o repasse exato do path
        location /auth-service {
            proxy_pass http://127.0.0.1:8001;
        }

        # 2. Flag Service
        location /flag-service {
            proxy_pass http://127.0.0.1:8002;
        }

        # 3. Targeting Service
        location /targeting-service {
            proxy_pass http://127.0.0.1:8003;
        }

        # 4. Evaluation Service
        location /evaluation-service {
            proxy_pass http://127.0.0.1:8004;
        }

        # 5. Analytics Service
        location /analytics-service {
            proxy_pass http://127.0.0.1:8005;
        }
    }
}