---
- hosts: localhost
  gather_facts: no
  vars:
    env_dir: "{{ env | default('k8s_kind') }}"
    base_path: "../../../{{ env_dir }}"
  tasks:
    - name: "Iniciando deploy no ambiente: {{ env_dir }}"
      debug:
        msg: "Aplicando manifestos de {{ base_path }}"

    - name: Add prometheus-community Helm repo
      ansible.builtin.command:
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
      register: output1
      ignore_errors: yes

    - name: Verificar a saída do output1
      debug:
        var: output1.stdout_lines
      ignore_errors: yes

    - name: Repo update
      ansible.builtin.command:
        helm repo update
      register: output2
      ignore_errors: yes

    - name: Verificar a saída do output2
      debug:
        var: output2.stdout_lines
      ignore_errors: yes

    - name: Install prometheus-community kube-prometheus-stack via Helm
      ansible.builtin.command: >
        helm install monitoring prometheus-community/kube-prometheus-stack \
        -n monitoring-ns \
        --set grafana.service.type=ClusterIP \
        --set-json grafana.service.annotations='{"cloud.google.com/backend-config": "iap-backend-config"}'
      register: output3
      ignore_errors: yes

    - name: Verificar a saída do output4
      debug:
        var: output3.stdout_lines
      ignore_errors: yes

    - name: Install prometheus-community kube-prometheus-stack via Helm
      ansible.builtin.command:
        kubectl apply -f {{ base_path }}/monitoring/
      register: output4
      ignore_errors: yes

    - name: Verificar a saída do output4
      debug:
        var: output4.stdout_lines
      ignore_errors: yes
