---
apiVersion: v1
kind: Secret
metadata:
  name: analytics-secrets
  namespace: analytics-ns
type: Opaque
stringData:
  PORT: "8005"
  AWS_SQS_URL: https://sqs.us-east-1.amazonaws.com/129874725379/toggle-master-analytics
  AWS_DYNAMODB_TABLE: ToggleMasterAnalytics
  AWS_REGION: us-east-1
  PROJECT_ID: ces-igniteprogram
