apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: analytics-ns

# 1. Correção do Ciclo: Liste os arquivos explicitamente
resources:
- analytics-health-check.yaml
- analytics-keda.yaml
- analytics-netpol.yaml
- analytics-service-deployment.yaml
- analytics-service-pdb.yaml
- analytics-service-secret.yaml
- analytics-service-serviceaccount.yaml
- analytics-service-svc.yaml
- analytics-trigger.yaml

# 2. Correção do Warning: Usando a nova sintaxe de labels
labels:
- includeSelectors: true
  pairs:
    app: analytics-service

# (O bloco patchesStrategicMerge foi removido, pois o deployment já está em resources)

images:
- name: analytics-service
  newName: southamerica-east1-docker.pkg.dev/ces-igniteprogram/artreg-analytics/analytics-service
  newTag: 5a1d1ec796b1fce1f60e82b59f71fdc01400d600
