---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-targeting-pvc
  namespace: targeting-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
