---
apiVersion: v1
kind: Secret
metadata:
  name: targeting-secrets
  namespace: targeting-ns
type: Opaque
stringData:
  DB_HOST: db-targeting-service
  DB_PORT: "5432"
  DB_NAME: targeting_db
  DB_USER: user
  DB_PASSWORD: password
  DATABASE_URL: postgres://user:password@db-targeting-service:5432/targeting_db
  AUTH_SERVICE_URL: http://auth-service.auth-ns:80/auth-service
  PORT: "8003"
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  POSTGRES_DB: targeting_db
