---
apiVersion: v1
kind: Secret
metadata:
  name: analytics-secrets
  namespace: analytics-ns
type: Opaque
stringData:
  PORT: "8005"
  AWS_SQS_URL: XXX
  AWS_DYNAMODB_TABLE: ToggleMasterAnalytics
  AWS_REGION: XXX
  AWS_ACCESS_KEY_ID: XXX
  AWS_SECRET_ACCESS_KEY: XXX
  AWS_SESSION_TOKEN: XXX
