---
apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: auth-ns
type: Opaque
stringData:
  MASTER_KEY: super-secret-master-key
  PORT: "8001"
  POSTGRES_DB: auth_db
  POSTGRES_USER: devops
  DB_HOST: "127.0.0.1"
  DB_PORT: "5432"
  CLOUDSQL_CONNECTION_NAME: ces-igniteprogram:southamerica-east1:sql-rhuan-auth
  PROJECT_ID: ces-igniteprogram
  NAME_SECRET_MANAGER: sm-auth-db
