apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: auth-service-hc-policy
  namespace: auth-ns
spec:
  default:
    checkIntervalSec: 5
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 3
    config:
      type: HTTP
      httpHealthCheck:
        port: 8001
        requestPath: /health
  targetRef:
    group: ""
    kind: Service
    name: auth-service
