---
apiVersion: v1
kind: Secret
metadata:
  name: job-secrets
  namespace: job-ns
type: Opaque
stringData:
  PROJECT_ID: ces-igniteprogram
  REGION_GCP: southamerica-east1
  DB_USER: devops
  AUTH_NAME_SECRET_MANAGER: sm-auth-db
  FLAG_NAME_SECRET_MANAGER: sm-flag-db
  TARGETING_NAME_SECRET_MANAGER: sm-targeting-db
  NAME_REDIS: redis-rhuan
  MASTER_KEY: super-secret-master-key
  AUTH_SERVICE_URL: http://auth-service.auth-ns:80/auth-service
  NAME_SM_ACCESS_KEY_ID: sm-aws-access-key-id
  NAME_SM_SECRET_ACCESS_KEY: sm-aws-secret-access-key
  NAME_SM_SESSION_TOKEN: sm-aws-session-token
  NAME_PERSONAL_ACCESS_TOKEN_GH: sm-personal-access-token-gh
  NAME_SM_SQS_QUEUE_URL: sm-sqs-queue-url
