---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flag-service
  namespace: flag-ns
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: "25%"
      maxUnavailable: "25%"
  selector:
    matchLabels:
      app: flag-service
  template:
    metadata:
      labels:
        app: flag-service
    spec:
      containers:
        - name: flag-service
          image: flag-service:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /health
              port: 8002
            periodSeconds: 10
            initialDelaySeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 8002
            periodSeconds: 10
            initialDelaySeconds: 15
          ports:
            - containerPort: 8002
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: flag-secrets
                  key: DATABASE_URL
            - name: AUTH_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: flag-secrets
                  key: AUTH_SERVICE_URL
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: flag-secrets
                  key: PORT
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 300m
              memory: 100Mi
