---
apiVersion: v1
kind: Secret
metadata:
  name: flag-secrets
  namespace: flag-ns
type: Opaque
stringData:
  DATABASE_URL: postgres://user:password@db-flag-service:5432/flag_db
  PORT: "8002"
  AUTH_SERVICE_URL: http://auth-service.auth-ns:80/auth-service
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  POSTGRES_DB: flag_db
  DB_HOST: db-flag-service
  DB_PORT: "5432"
