# argocd/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: evaluation-application
  namespace: argocd
  labels:
    app: evaluation-service
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:rhuanlasoares/fiap-tech-challenge03.git
    targetRevision: main
    path: k8s/evaluation-service
  destination:
    server: https://kubernetes.default.svc
    namespace: evaluation-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true