---
apiVersion: v1
kind: Secret
metadata:
  name: evaluation-secrets
  namespace: evaluation-ns
type: Opaque
stringData:
  MASTER_KEY: super-secret-master-key
  AUTH_SERVICE_URL: http://auth-service.auth-ns:80/auth-service
  FLAG_SERVICE_URL: http://flag-service.flag-ns:80/flag-service
  TARGETING_SERVICE_URL: http://targeting-service.targeting-ns:80/targeting-service
  AWS_REGION: us-east-1
  PORT: "8004"
  NAME_REDIS: redis-rhuan
  PROJECT_ID: ces-igniteprogram
  REGION_GCP: southamerica-east1
