apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: evaluation-service-hc-policy
  namespace: evaluation-ns
spec:
  default:
    checkIntervalSec: 5
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 3
    config:
      type: HTTP
      httpHealthCheck:
        port: 8004
        requestPath: /health
  targetRef:
    group: ""
    kind: Service
    name: evaluation-service
